package util

import "math/rand"

var endingPhrasesSlice = []string{
	"Cogitated for",
	"Brewed for",
	"Crunched for",
	"Contemplated for",
	"Pondered for",
	"Ruminated for",
	"Reflected for",
	"Deliberated for",
	"Chewed on for",
	"Stewed on for",
	"Marinated in thought for",
	"Simmered on for",
	"Fermented on for",
	"Infused with thought for",
	"Percolated on for",
	"Steeped in contemplation for",
	"Sipped for",
	"Swirled in the mind for",
	"Distilled for",
	"Infused for",
	"Steeped for",
	"Fermented for",
	"Percolated for",
	"Marinated for",
	"Danced for",
	"Swirled for",
	"Scratched my head in agony for",
	"Sat in silence for",
	"Sat in a dark room for",
	"Sat in a corner for",
	"Scaffold for",
	"And then I realized it was DNS all along after",
	"Done in",
	"Done in a single night after",
	"I'm very fast. Done in",
	"Compiled and ran in",
	"Grep'd the entire internet in",
	"Checked the logs in",
	"Blamed DNS for",
	"Filed a Jira ticket and still finished in",
	"Pivoted through the network in",
	"Exfiltrated the data in",
	"Ran strings on the binary for",
	"Debugged in production in",
	"Skimmed the CVEs in",
	"Read the man page in",
	"Opened 47 Stack Overflow tabs and still finished in",
	"Waited for IT approval for exactly",
	"Asked ChatGPT and fact-checked the answer in",
	"Triaged and closed as won't fix in",
	"Patched in",
	"Zero-day'd in",
	"Escalated privileges in",
	"Pivoted laterally in",
	"Found the flag in",
	"Bypassed the WAF in",
	"Read the RFC in",
	"Submitted the CVE in",
	"Reversed the binary in",
	"Decompiled and recompiled in",
	"rm -rf'd the wrong directory and still finished in",
}

func GetRandEndingPhrase() string {
	return endingPhrasesSlice[rand.Intn(len(endingPhrasesSlice))]
}